image: "thanandorn/gkh:0.11.10"

before_script:
  - gcloud auth activate-service-account --key-file=$SVC_ACCT
  - gcloud config set project intrepid-signal-149714

deploy_iaas:
  script:
    - gcloud app deploy --project=intrepid-signal-149714 ./helloworld/app.yaml
