image: "google/cloud-sdk"

before_script:
  - gcloud auth activate-service-account --key-file=$SVC_ACCT
  - gcloud config set project intrepid-signal-149714
  - gcloud components install app-engine-go

deploy_iaas:
  script:
    - go get google.golang.org/appengine
    - gcloud app deploy --project=intrepid-signal-149714 ./helloworld/app.yaml
