image: "google/cloud-sdk"

before_script:
  - gcloud auth activate-service-account --key-file=$SVC_ACCT
  - gcloud config set project intrepid-signal-149714
  - apt-get -y install golang

deploy_iaas:
  script:
    - export GOPATH=$(pwd)
    - go get google.golang.org/appengine
    - gcloud app deploy --project=intrepid-signal-149714 ./iaas/app.yaml
